language: java
deploy:
  provider: heroku
  api_key:
    secure: XuRQXcPk+s35yySReCx1lJzkEj5ZK7F0WpQsYbIr70fiVyjFL8Tdh8REInbN0Kkrd8N1Kee/SoxGNDDUeklAfTIUD1SFvJfLQVA1mCeNmG970qgdz6/269DLlbQJfxAo5MK227JkaVHUAhkQGs6NB7zmwK9TPSGOIitB7Z1UTKRmjxPfISxKh5rA6MyA4u7/ifWEYNPKzn9YaYHkRjivoIW8r/xshnAvzE3cX+FFP5OZGGSwTtQ2aPdiprgGXLasYMUpkLoM4QkIBRH+Zi1LWXt0wirtut3E49N+MMZClLIw0Zaje58TcY8SsC3B3wsSgh888nsyK1W1QGuAYAYxSJir0OVsEks6qpPyxNGgnRDc5H2eCTRBddVSENkreaguD0vOV7K96ALlgTMEJZ3Ue/zfzFEyX6KKgQPG46jjInjqZHGNPqk904A9IfwfMBPKGKvdLRhNElPjMTQ4ksSnZaSXNaniBWb71q4H2FhO+VFct3KaAdjaR/2nIQ++vPKYRjJ62X0BBBsqGDg9jkuJd9RDIeI7H+hFS1ExfawmKM7pLozZWAArjlNFAJjGXacdHYExow1AZZG8OQcDQRH3MDRtoWfRhsHN10ZSxIyzfzlOsrYG2KfLEGo2xJ5LnKQiCa+vv0tGwvgRzH1m4awJ7Lk2CXM+JZp3qrmkOIuXJYY=
  app: intense-scrubland-63679
  on:
    repo: joergsesterhenn/chickenpi
