logging:
  level: INFO
  loggers:
    de.chickenpi: DEBUG
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081